### Seitenweite Variablen ###
title: KjG Goldbach
email: kjg-goldbach@gmx.de
url: http://kjg-goldbach.de
author: KjG Goldbach
description: Neuigkeiten und Aktionen der Katholischen jungen Gemeinde Goldbach
permalink: /:categories/:year/:month/:title/
# Anzahl der News-Posts auf der Hauptseite
frontpage-news: 4

### Build Settings ###
exclude: [new_post.py, readme.md, assets/fonts, Rakefile, Gemfile, Gemfile.lock]
include: [.htaccess]
markdown: kramdown
sass:
    sass_dir: assets/css
    style: compressed
atom:
  buildCommand:
    - /home/luke/.gem/ruby/2.4.0/bin/bundle
    - exec
    - jekyll
    - build
    - --config
    - _config.yml,_config-dev.yml

### Collections ###
collections:
  calendar:
    relative_directory: '_kalender/termine'
  gruppenstunden:
    relative_directory: '_kalender/gruppenstunden'
  pompfen:
    relative_directory: '_collections/pompfen'
  aktionen:
    relative_directory: '_collections/aktionen'

### Defaults ###
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerpt_separator: <!--more-->
      category: aktuelles

### Plugins ###
gems: [jekyll-paginate, jekyll-feed, jekyll-redirect-from]

### Pagination ###
paginate: 5
paginate_path: "/aktuelles/page:num/"

### Feed Settings ###
feed:
  path: aktuelles/atom.xml
calfeed_path: aktuelles/events.ics
